version: '2'
services:
 vlan:
  image: omega/vlan-netplugin:0.1.0
  command: start
  network: host
  privileged: true
  pid : host
  environment:
    - "affinity:container!=*vlan*"
  restart: always
  volumes:
    - /run/docker/plugins:/run/docker/plugins
    - /var/run/docker/netns/:/var/run/docker/netns
    - /var/run/docker.sock:/var/run/docker.sock
